### ISSUE TITLE
No credentials given in directions

### ISSUE THREAD

**Issue by softwaremike** [NextCenturyCorporation/ozp-docker-runner#1]
After starting ozp-docker-runner, I attempt to hit the URL given in the directions.  This asks me for a username/password.  I do not see any login info in the directions on Github?

**Comment by kdrumm** [comment]
Thanks for letting us know about that oversight.  I have updated the readme.md.  You can use the user/password combination wsmith/password.  Also see https://github.com/ozoneplatform/ozp-ansible#quickstart for more user/password combinations.
