### ISSUE TITLE
Possible to include Dockerfiles?

### ISSUE THREAD

**Issue by alienatorZ** [NextCenturyCorporation/ozp-docker-runner#2]
Hi,
I would like to request the Dockerfiles for the containers. I would like to further customize a deployment.

Thanks!

**Comment by kdrumm** [comment]
The Dockerfiles for the containers are not part of the FOSS software suite, but we can put you in touch with our consulting services group if you are interested in contracting for support.  Please email us at ozone-sales@nextcentury.com.
